name: auramaxx_app
description: Auramaxx ESP32 BLE Light Controller
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.36.8
  permission_handler: ^11.3.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/auramaxx_logo.png
    - assets/Car.png
    - assets/bground.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/auramaxx_icon.png"

flutter_native_splash:
  color: "#131313" # background color
  android: true
  ios: true

  android_gravity: center
  ios_content_mode: scaleAspectFit
